language: scala
scala:
  - 2.11.8

cache:
  directories:
    - $HOME/.m2
    - ./build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: yaooqinn@hotmail.com
    name: Kent Yao
    on:
      branch: master

jobs:
  include:
    - stage: spark2.4
      language: scala
      script: mvn clean install -Pspark-2.4 -Dmaven.javadoc.skip=true -B -V
    - stage: spark2.3
      language: scala
      script: mvn clean install -Pspark-2.3 -Dmaven.javadoc.skip=true -B -V
    - stage: spark2.2
      language: scala
      script: mvn clean install -Pspark-2.2 -Dmaven.javadoc.skip=true -B -V
    - stage: spark2.1
      language: scala
      script: mvn clean install -Pspark-2.1 -Dmaven.javadoc.skip=true -B -V

